spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book-reviews
      username: book
      password: book
      authentication-database: admin


jwt.key: 7A24432646294A404E635266556A586E327234753778214125442A472D4B6150